#!/usr/bin/env python3
"""
Confluence Page Creator/Updater from Markdown

This script creates or updates Confluence pages from Markdown files. It converts
Markdown content to HTML using the Python markdown library and uploads it to
Confluence via the REST API.

USAGE:
    # Create a new page
    python update-confluence-page-w-markdown.py -t "Page Title" -i path/to/file.md
    
    # Create a page in a specific space with custom parent
    python update-confluence-page-w-markdown.py -t "Page Title" -i file.md -s "SPACE" -p "123456"
    
    # Update an existing page
    python update-confluence-page-w-markdown.py -t "Updated Title" -i file.md -r "789012"
    
    # Use custom config file
    python update-confluence-page-w-markdown.py -t "Page Title" -i file.md -c custom-config.yaml

REQUIRED ARGUMENTS:
    -t, --title      Title of the Confluence page
    -i, --input      Path to the input Markdown file

OPTIONAL ARGUMENTS:
    -c, --config     Path to config YAML file (default: data/config/confluence.yaml)
    -s, --space      Confluence space key (default: ~dvreeman)
    -p, --parent     Parent page ID for new pages (default: 345541283)
    -r, --replace    Page ID to update (if provided, updates instead of creating)

CONFIGURATION FILE:
    The config file must be a YAML file with the following structure:
    
    base_url: https://your-confluence-instance.atlassian.net
    bearer_token: your_bearer_token_here
    
    The bearer_token should be a Confluence API token or OAuth bearer token
    with appropriate permissions to create/update pages in the target space.

MARKDOWN SUPPORT:
    This script supports standard Markdown features via the Python markdown library:
    - Headers (#, ##, ###, etc.)
    - Bold and italic text
    - Lists (ordered and unordered)
    - Links and images
    - Tables (via 'tables' extension)
    - Fenced code blocks (via 'fenced_code' extension)
    - Table of contents (via 'toc' extension)
    
    Extensions enabled: tables, fenced_code, toc

MERMAID DIAGRAMS:
    ✅ AUTOMATIC CONVERSION: Mermaid diagrams in Markdown code blocks are
    automatically converted to PNG images and uploaded to Confluence.
    
    Example Mermaid code block:
    ```mermaid
    graph TD
        A[Start] --> B[End]
    ```
    
    This will be:
    1. Detected in the markdown file
    2. Rendered to a PNG image using mermaid-cli (mmdc)
    3. Uploaded to Confluence as an attachment
    4. Replaced in the HTML with an image reference
    
    REQUIREMENTS:
    - mermaid-cli must be installed: npm install -g @mermaid-js/mermaid-cli
    - The 'mmdc' command must be available in your PATH
    
    The images are uploaded as attachments to the page and embedded inline.
    Temporary files created during rendering are automatically cleaned up.

TABLE OF CONTENTS (TOC):
    ✅ AUTOMATIC CONVERSION: Markdown table of contents generated by the
    'toc' extension are automatically converted to Confluence's TOC macro.
    
    The markdown TOC extension generates HTML like:
    <div class="toc">
      <ul>
        <li><a href="#section">Section</a></li>
      </ul>
    </div>
    
    This is automatically replaced with Confluence's TOC macro:
    <ac:structured-macro ac:name="toc"/>
    
    The Confluence TOC macro automatically generates a working table of contents
    based on the page headings, and all links will work correctly in Confluence.

EXAMPLES:
    # Basic page creation
    python update-confluence-page-w-markdown.py \\
        -t "My Documentation Page" \\
        -i docs/my-page.md
    
    # Update existing page
    python update-confluence-page-w-markdown.py \\
        -t "Updated Documentation" \\
        -i docs/my-page.md \\
        -r "123456789"
    
    # Create page in different space
    python update-confluence-page-w-markdown.py \\
        -t "Team Notes" \\
        -i notes.md \\
        -s "TEAM" \\
        -p "987654321"

RETURN CODES:
    0 - Success
    1 - Error (config file missing, API error, file not found, etc.)

DEPENDENCIES:
    - requests: For HTTP API calls to Confluence
    - pyyaml: For reading configuration files
    - markdown: For converting Markdown to HTML
    - mermaid-cli: For rendering Mermaid diagrams (npm install -g @mermaid-js/mermaid-cli)

AUTHOR:
    Created for HL7 Standards Development Data project
"""

import argparse
import json
import requests
import yaml
import time
import re
import subprocess
import tempfile
import os
import hashlib
from markdown import markdown
from urllib.parse import urljoin

def load_config(config_path):
    """Load configuration from YAML file"""
    with open(config_path, 'r') as f:
        return yaml.safe_load(f)

def get_page_info(base_url, bearer_token, page_id):
    """Get existing page information"""
    headers = {
        "Authorization": f"Bearer {bearer_token}",
        "Content-Type": "application/json"
    }
    
    url = f"{base_url}/rest/api/content/{page_id}"
    response = requests.get(url, headers=headers)
    
    if response.status_code == 200:
        return response.json()
    else:
        print(f"❌ Error getting page info: {response.status_code}")
        print(response.text)
        return None

def extract_mermaid_blocks(markdown_text):
    """Extract all Mermaid code blocks from markdown text"""
    # Pattern to match fenced code blocks with mermaid language
    pattern = r'```mermaid\s*\n(.*?)```'
    matches = re.finditer(pattern, markdown_text, re.DOTALL | re.MULTILINE)
    
    blocks = []
    for match in matches:
        blocks.append({
            'full_match': match.group(0),
            'content': match.group(1).strip(),
            'start': match.start(),
            'end': match.end()
        })
    
    return blocks

def render_mermaid_to_png(mermaid_code, output_path):
    """Render Mermaid diagram code to PNG image using mermaid-cli"""
    try:
        # Check if mmdc is available
        subprocess.run(['mmdc', '--version'], 
                      capture_output=True, 
                      check=True, 
                      timeout=5)
    except (subprocess.CalledProcessError, FileNotFoundError, subprocess.TimeoutExpired):
        raise RuntimeError(
            "mermaid-cli (mmdc) not found. Install it with: npm install -g @mermaid-js/mermaid-cli"
        )
    
    # Create temporary mermaid file
    with tempfile.NamedTemporaryFile(mode='w', suffix='.mmd', delete=False) as tmp_mmd:
        tmp_mmd.write(mermaid_code)
        tmp_mmd_path = tmp_mmd.name
    
    try:
        # Render to PNG
        result = subprocess.run(
            ['mmdc', '-i', tmp_mmd_path, '-o', output_path, '-b', 'transparent'],
            capture_output=True,
            text=True,
            timeout=30
        )
        
        if result.returncode != 0:
            raise RuntimeError(f"mermaid-cli failed: {result.stderr}")
        
        if not os.path.exists(output_path):
            raise RuntimeError(f"Output file was not created: {output_path}")
        
        return True
    finally:
        # Clean up temporary mermaid file
        if os.path.exists(tmp_mmd_path):
            os.unlink(tmp_mmd_path)

def get_attachment_by_name(base_url, bearer_token, page_id, attachment_name):
    """Get an attachment by filename if it exists"""
    headers = {
        "Authorization": f"Bearer {bearer_token}",
        "Content-Type": "application/json"
    }
    
    url = f"{base_url}/rest/api/content/{page_id}/child/attachment"
    params = {"filename": attachment_name}
    
    response = requests.get(url, headers=headers, params=params)
    
    if response.status_code == 200:
        data = response.json()
        if data.get('results') and len(data['results']) > 0:
            return data['results'][0]
    return None

def delete_attachment(base_url, bearer_token, page_id, attachment_id):
    """Delete an attachment from a Confluence page"""
    headers = {
        "Authorization": f"Bearer {bearer_token}",
        "X-Atlassian-Token": "no-check"
    }
    
    url = f"{base_url}/rest/api/content/{page_id}/child/attachment/{attachment_id}"
    response = requests.delete(url, headers=headers)
    
    return response.status_code == 204

def upload_image_to_confluence(base_url, bearer_token, page_id, image_path, image_name):
    """Upload an image file to Confluence as an attachment to a page.
    If an attachment with the same name exists, it will be deleted first."""
    headers = {
        "Authorization": f"Bearer {bearer_token}",
        "X-Atlassian-Token": "no-check"  # Required for file uploads
    }
    
    # Check if attachment with same name already exists
    existing_attachment = get_attachment_by_name(base_url, bearer_token, page_id, image_name)
    if existing_attachment:
        print(f"  🗑️  Deleting existing attachment: {image_name}")
        if delete_attachment(base_url, bearer_token, page_id, existing_attachment['id']):
            print(f"  ✅ Deleted existing attachment")
        else:
            print(f"  ⚠️  Warning: Failed to delete existing attachment, will try to upload anyway")
    
    # Upload attachment
    url = f"{base_url}/rest/api/content/{page_id}/child/attachment"
    
    with open(image_path, 'rb') as f:
        files = {
            'file': (image_name, f, 'image/png')
        }
        data = {
            'comment': 'Uploaded Mermaid diagram'
        }
        
        response = requests.post(url, headers=headers, files=files, data=data)
    
    if response.status_code == 200:
        attachment_data = response.json()['results'][0]
        return attachment_data
    else:
        print(f"⚠️  Warning: Failed to upload image {image_name}: {response.status_code}")
        print(response.text)
        return None

def process_mermaid_diagrams(markdown_text, base_url, bearer_token, page_id):
    """
    Process markdown text to convert Mermaid diagrams to images.
    Returns tuple: (modified_markdown_text, list_of_image_info_dicts)
    
    Each image_info dict contains:
    - 'image_path': path to rendered PNG file
    - 'image_name': filename for Confluence attachment
    - 'block_match': original Mermaid code block text
    - 'block_start': start position in original text
    - 'block_end': end position in original text
    """
    mermaid_blocks = extract_mermaid_blocks(markdown_text)
    
    if not mermaid_blocks:
        return markdown_text, []  # No Mermaid diagrams found
    
    print(f"📊 Found {len(mermaid_blocks)} Mermaid diagram(s) to convert...")
    
    image_info_list = []
    
    # Process each Mermaid block
    for i, block in enumerate(mermaid_blocks):
        try:
            # Generate unique filename based on content hash
            content_hash = hashlib.md5(block['content'].encode()).hexdigest()[:8]
            image_name = f"mermaid-diagram-{content_hash}.png"
            
            # Create temporary PNG file
            with tempfile.NamedTemporaryFile(suffix='.png', delete=False) as tmp_png:
                tmp_png_path = tmp_png.name
            
            # Render Mermaid to PNG
            print(f"  🎨 Rendering diagram {i+1}/{len(mermaid_blocks)}...")
            render_mermaid_to_png(block['content'], tmp_png_path)
            
            # Upload to Confluence if page_id is available
            attachment = None
            if page_id:
                print(f"  📤 Uploading {image_name}...")
                attachment = upload_image_to_confluence(
                    base_url, bearer_token, page_id, tmp_png_path, image_name
                )
                if attachment:
                    print(f"  ✅ Diagram converted and uploaded")
                else:
                    print(f"  ⚠️  Diagram rendered but upload failed")
            
            # Store image info
            image_info_list.append({
                'image_path': tmp_png_path,
                'image_name': image_name,
                'block_match': block['full_match'],
                'block_content': block['content'],
                'block_start': block['start'],
                'block_end': block['end'],
                'uploaded': attachment is not None
            })
        
        except Exception as e:
            print(f"  ❌ Error processing Mermaid diagram {i+1}: {e}")
            # Keep the original Mermaid block if conversion fails
            continue
    
    # Replace Mermaid blocks with image references in markdown
    # Always replace, even if not uploaded yet (for new pages, we'll upload after creation)
    modified_text = markdown_text
    
    # Use direct string replacement for each block (more reliable than position-based)
    for image_info in image_info_list:
        # Replace Mermaid code block with markdown image syntax
        # This will be converted to HTML img tag, then replaced with Confluence macro
        replacement = f'![Mermaid Diagram]({image_info["image_name"]})'
        
        # Replace the full Mermaid block with image reference
        if image_info['block_match'] in modified_text:
            modified_text = modified_text.replace(image_info['block_match'], replacement, 1)
            print(f"  ✅ Replaced Mermaid block with image reference: {image_info['image_name']}")
        else:
            print(f"  ⚠️  Warning: Could not find Mermaid block to replace for {image_info['image_name']}")
            # Try using positions as fallback
            try:
                modified_text = (
                    modified_text[:image_info['block_start']] +
                    replacement +
                    modified_text[image_info['block_end']:]
                )
            except Exception as e:
                print(f"  ❌ Error replacing block: {e}")
    
    # Verify all Mermaid blocks were replaced
    remaining_mermaid = extract_mermaid_blocks(modified_text)
    if remaining_mermaid:
        print(f"  ⚠️  Warning: {len(remaining_mermaid)} Mermaid block(s) still remain in processed markdown")
        # Try one more pass with remaining blocks
        for block in remaining_mermaid:
            # Find a matching image_info by content
            for image_info in image_info_list:
                if block['content'].strip() == image_info.get('block_content', '').strip():
                    replacement = f'![Mermaid Diagram]({image_info["image_name"]})'
                    modified_text = modified_text.replace(block['full_match'], replacement, 1)
                    print(f"  ✅ Replaced remaining Mermaid block with image reference: {image_info['image_name']}")
                    break
    
    return modified_text, image_info_list

def replace_markdown_images_with_confluence_macros(html_content, image_info_list):
    """
    Replace markdown image tags in HTML with Confluence storage format image macros.
    Handles various HTML formats that markdown might generate.
    """
    for image_info in image_info_list:
        if image_info['uploaded']:
            # Find the markdown image in HTML and replace with Confluence macro
            # Markdown converts ![alt](filename) to <img alt="alt" src="filename" />
            # We need to replace with Confluence attachment format
            escaped_name = re.escape(image_info["image_name"])
            
            # Try multiple patterns to catch different HTML structures
            patterns = [
                # img tag wrapped in paragraph with whitespace
                rf'<p>\s*<img[^>]*src=["\']{escaped_name}["\'][^>]*/?>\s*</p>',
                # Standalone img tag
                rf'<img[^>]*src=["\']{escaped_name}["\'][^>]*/?>',
                # img tag with newlines
                rf'<img[^>]*\s+src=["\']{escaped_name}["\'][^>]*/?>',
            ]
            
            confluence_image = f'<ac:image ac:align="center"><ri:attachment ri:filename="{image_info["image_name"]}" /></ac:image>'
            
            replaced = False
            for pattern in patterns:
                if re.search(pattern, html_content, flags=re.IGNORECASE | re.MULTILINE | re.DOTALL):
                    html_content = re.sub(pattern, confluence_image, html_content, flags=re.IGNORECASE | re.MULTILINE | re.DOTALL)
                    replaced = True
                    break
            
            if not replaced:
                # Fallback: try to find any reference to the image name and replace
                # This handles edge cases where markdown might format differently
                print(f"  ⚠️  Warning: Could not find image reference for {image_info['image_name']} in HTML")
                # Try a more aggressive search
                if image_info['image_name'] in html_content:
                    # Look for any img tag that might contain this filename
                    fallback_pattern = rf'<img[^>]*{escaped_name}[^>]*/?>'
                    html_content = re.sub(fallback_pattern, confluence_image, html_content, flags=re.IGNORECASE | re.MULTILINE | re.DOTALL)
    
    return html_content

def replace_markdown_toc_with_confluence_macro(html_content):
    """
    Replace markdown TOC HTML with Confluence TOC macro.
    
    Handles two types of TOC:
    1. Auto-generated TOC from markdown 'toc' extension:
       <div class="toc">
         <ul>
           <li><a href="#section">Section</a></li>
         </ul>
       </div>
    
    2. Manual TOC (heading + list of anchor links):
       <h2>Table of Contents</h2>
       <ul>
         <li><a href="#section">Section</a></li>
       </ul>
    
    Confluence uses: <h2>Table of Contents</h2><ac:structured-macro ac:name="toc"/>
    """
    toc_heading = '<h2>Table of Contents</h2>'
    confluence_toc = '<ac:structured-macro ac:name="toc"/>'
    toc_with_heading = toc_heading + '\n' + confluence_toc
    
    print(f"  🔍 Looking for markdown TOC in HTML...")
    
    # Function to match nested divs properly by counting opening/closing tags
    def find_nested_div(match_start, html, tag='div'):
        """Find the complete div including nested content by counting opening/closing tags"""
        pos = match_start
        start_pos = match_start
        
        # Find the opening tag
        tag_pattern = rf'<{tag}[^>]*>'
        tag_match = re.search(tag_pattern, html[pos:], re.IGNORECASE)
        if not tag_match:
            return None
        start_pos = pos + tag_match.start()
        pos = pos + tag_match.end()
        depth = 1
        
        # Find the matching closing tag by counting nested tags
        open_pattern = rf'<{tag}[^>]*>'
        close_pattern = rf'</{tag}>'
        
        while pos < len(html) and depth > 0:
            # Look for next opening or closing tag
            next_open = re.search(open_pattern, html[pos:], re.IGNORECASE)
            next_close = re.search(close_pattern, html[pos:], re.IGNORECASE)
            
            if next_open and next_close:
                if next_open.start() < next_close.start():
                    depth += 1
                    pos += next_open.end()
                else:
                    depth -= 1
                    if depth == 0:
                        return (start_pos, pos + next_close.end())
                    pos += next_close.end()
            elif next_close:
                depth -= 1
                if depth == 0:
                    return (start_pos, pos + next_close.end())
                pos += next_close.end()
            else:
                break
        
        return None
    
    # Pattern to find opening div tags with toc class/id (flexible attribute order)
    # Matches: <div class="toc">, <div id="toc">, <div class="toc" id="something">, etc.
    toc_opening_patterns = [
        r'<div[^>]*class\s*=\s*["\']toc["\'][^>]*>',  # class="toc" or class='toc'
        r'<div[^>]*id\s*=\s*["\']toc["\'][^>]*>',     # id="toc" or id='toc'
        r'<div[^>]*class\s*=\s*["\'][^"\']*toc[^"\']*["\'][^>]*>',  # class contains "toc"
    ]
    
    matches_found = []
    for pattern in toc_opening_patterns:
        for match in re.finditer(pattern, html_content, re.IGNORECASE):
            nested_match = find_nested_div(match.start(), html_content, 'div')
            if nested_match:
                # Check if we already have this match (avoid duplicates)
                if not any(m[0] == nested_match[0] for m in matches_found):
                    matches_found.append(nested_match)
                    toc_snippet = html_content[nested_match[0]:min(nested_match[1], nested_match[0]+100)]
                    print(f"  📋 Found TOC div at position {nested_match[0]}-{nested_match[1]}")
                    print(f"      Snippet: {toc_snippet[:80]}...")
    
    # Also check for nav tags
    nav_patterns = [
        r'<nav[^>]*class\s*=\s*["\']toc["\'][^>]*>',
        r'<nav[^>]*id\s*=\s*["\']toc["\'][^>]*>',
    ]
    for pattern in nav_patterns:
        for match in re.finditer(pattern, html_content, re.IGNORECASE):
            nested_match = find_nested_div(match.start(), html_content, 'nav')
            if nested_match:
                if not any(m[0] == nested_match[0] for m in matches_found):
                    matches_found.append(nested_match)
                    print(f"  📋 Found TOC nav at position {nested_match[0]}-{nested_match[1]}")
    
    # Also detect manual TOC sections: heading with "Table of Contents" or "Contents" followed by anchor links
    # Pattern: <h1-h6>Table of Contents</h1-h6> followed by <ul> or <ol> with anchor links
    # IMPORTANT: Match only within a single heading tag, not across multiple headings
    toc_heading_patterns = [
        r'<h[1-6][^>]*>Table\s+of\s+Contents</h[1-6]>',  # Exact match within single tag
        r'<h[1-6][^>]*>Contents</h[1-6]>',  # Exact match within single tag
        r'<h[1-6][^>]*>TOC</h[1-6]>',  # Exact match within single tag
    ]
    
    def find_nested_list(match_start, html, tag='ul'):
        """Find the complete list including nested content by counting opening/closing tags"""
        pos = match_start
        start_pos = match_start
        
        # Find the opening tag
        tag_pattern = rf'<{tag}[^>]*>'
        tag_match = re.search(tag_pattern, html[pos:], re.IGNORECASE)
        if not tag_match:
            return None
        start_pos = pos + tag_match.start()
        pos = pos + tag_match.end()
        depth = 1
        
        # Find the matching closing tag by counting nested tags
        open_pattern = rf'<{tag}[^>]*>'
        close_pattern = rf'</{tag}>'
        
        while pos < len(html) and depth > 0:
            # Look for next opening or closing tag
            next_open = re.search(open_pattern, html[pos:], re.IGNORECASE)
            next_close = re.search(close_pattern, html[pos:], re.IGNORECASE)
            
            if next_open and next_close:
                if next_open.start() < next_close.start():
                    depth += 1
                    pos += next_open.end()
                else:
                    depth -= 1
                    if depth == 0:
                        return (start_pos, pos + next_close.end())
                    pos += next_close.end()
            elif next_close:
                depth -= 1
                if depth == 0:
                    return (start_pos, pos + next_close.end())
                pos += next_close.end()
            else:
                break
        
        return None
    
    for heading_pattern in toc_heading_patterns:
        for heading_match in re.finditer(heading_pattern, html_content, re.IGNORECASE | re.DOTALL):
            heading_end = heading_match.end()
            
            # Look for a list (ul or ol) immediately after the heading
            # Check for whitespace/newlines between heading and list
            list_opening_pattern = r'[\s\n]*(<(?:ul|ol)[^>]*>)'
            list_opening_match = re.search(list_opening_pattern, html_content[heading_end:], re.IGNORECASE)
            
            if list_opening_match:
                list_start_pos = heading_end + list_opening_match.start(1)
                # Extract tag name ('ul' or 'ol') from the opening tag
                tag_match = re.search(r'<(ul|ol)', list_opening_match.group(1), re.IGNORECASE)
                tag_name = tag_match.group(1).lower() if tag_match else 'ul'
                # Find the complete nested list
                nested_list = find_nested_list(list_start_pos, html_content, tag_name)
                
                if nested_list:
                    # Check if the list contains anchor links (href="#...")
                    list_content = html_content[nested_list[0]:nested_list[1]]
                    if re.search(r'href\s*=\s*["\']#', list_content, re.IGNORECASE):
                        # Found a manual TOC: heading + list with anchor links
                        toc_start = heading_match.start()
                        toc_end = nested_list[1]
                        
                        # Check if we already have this match
                        if not any(m[0] == toc_start for m in matches_found):
                            matches_found.append((toc_start, toc_end))
                            snippet = html_content[toc_start:min(toc_end, toc_start+150)]
                            print(f"  📋 Found manual TOC (heading + list) at position {toc_start}-{toc_end}")
                            print(f"      Snippet: {snippet[:120]}...")
                        break  # Only match first occurrence per heading pattern
    
    # Replace all found TOC structures
    if matches_found:
        # Replace from end to preserve positions
        for start, end in reversed(matches_found):
            html_content = html_content[:start] + toc_with_heading + html_content[end:]
        print(f"  ✅ Replaced {len(matches_found)} markdown TOC(s) with H2 heading and Confluence TOC macro")
        return html_content
    
    # Fallback: try simpler regex patterns if nested matching didn't work
    # This handles cases where there are no nested divs inside the TOC div
    fallback_patterns = [
        (r'<div[^>]*class\s*=\s*["\']toc["\'][^>]*>.*?</div>', "div with class=toc"),
        (r'<div[^>]*id\s*=\s*["\']toc["\'][^>]*>.*?</div>', "div with id=toc"),
        (r'<nav[^>]*class\s*=\s*["\']toc["\'][^>]*>.*?</nav>', "nav with class=toc"),
    ]
    
    for pattern, desc in fallback_patterns:
        matches = list(re.finditer(pattern, html_content, flags=re.IGNORECASE | re.MULTILINE | re.DOTALL))
        if matches:
            for match in reversed(matches):
                html_content = html_content[:match.start()] + toc_with_heading + html_content[match.end():]
            print(f"  ✅ Replaced markdown TOC ({desc}, fallback) with H2 heading and Confluence TOC macro")
            return html_content
    
    # Check if TOC indicators exist but weren't matched
    if re.search(r'class\s*=\s*["\']toc', html_content, re.IGNORECASE) or \
       re.search(r'id\s*=\s*["\']toc', html_content, re.IGNORECASE):
        print(f"  ⚠️  Warning: Found TOC indicators but couldn't match TOC structure")
        # Try to show a snippet for debugging
        toc_match = re.search(r'<div[^>]*class\s*=\s*["\']toc["\'][^>]*>', html_content, re.IGNORECASE)
        if toc_match:
            snippet_start = toc_match.start()
            snippet = html_content[snippet_start:min(snippet_start+200, len(html_content))]
            print(f"      Found TOC opening tag, snippet: {snippet[:150]}...")
    else:
        print(f"  ℹ️  No TOC found in HTML content")
    
    return html_content

def fix_confluence_anchor_links(html_content):
    """
    Fix anchor links in HTML to work with Confluence's anchor system.
    Confluence automatically generates anchors from headers, but the format differs.
    This function fixes links that use markdown-style anchors (#section-name) to work
    with Confluence's anchor format.
    
    Note: Confluence's TOC macro automatically handles anchor links correctly,
    but manual anchor links in the content may need fixing.
    """
    # Pattern to match anchor links: <a href="#anchor-name">text</a>
    # Confluence uses anchors based on header text, but we'll let the TOC macro handle most cases
    # For manual links, we can try to preserve them - Confluence may auto-convert them
    
    # Extract all header IDs that markdown might have generated
    # Markdown TOC extension typically creates IDs like: id="section-name" or id="section_name"
    header_id_pattern = r'<h[1-6][^>]*id=["\']([^"\']+)["\'][^>]*>'
    header_ids = set(re.findall(header_id_pattern, html_content, re.IGNORECASE))
    
    # Fix anchor links to use the same IDs
    # Pattern: <a href="#anchor-name"> or <a href='#anchor-name'>
    anchor_link_pattern = r'<a\s+href=["\']#([^"\']+)["\'][^>]*>'
    
    def fix_anchor(match):
        anchor_name = match.group(1)
        # Check if this anchor matches a header ID
        # Confluence will auto-generate anchors, but we can ensure consistency
        # by keeping the href as-is (Confluence should handle it)
        return match.group(0)  # Keep original for now - Confluence handles most cases
    
    # For now, we'll keep anchor links as-is since Confluence's TOC macro handles them
    # and Confluence auto-generates anchors from headers
    # If needed, we can add more sophisticated anchor fixing here
    
    return html_content

def create_page(config, space_key, title, markdown_file, parent_id=None):
    """Create a new Confluence page from markdown"""
    base_url = config['base_url'].rstrip("/")
    bearer_token = config['bearer_token']
    headers = {
        "Authorization": f"Bearer {bearer_token}",
        "Content-Type": "application/json"
    }

    # Load markdown
    with open(markdown_file, "r", encoding="utf-8") as f:
        md_text = f.read()
    
    # Process Mermaid diagrams (render to images, but can't upload until page exists)
    processed_md, image_info_list = process_mermaid_diagrams(
        md_text, base_url, bearer_token, None  # page_id is None for new pages
    )
    
    # Convert markdown to HTML (with placeholder image references)
    html_content = markdown(processed_md, extensions=["tables", "fenced_code", "toc"])
    
    # Replace markdown TOC with Confluence TOC macro
    print(f"📑 Processing table of contents...")
    html_content = replace_markdown_toc_with_confluence_macro(html_content)
    
    # Fix anchor links for Confluence compatibility
    html_content = fix_confluence_anchor_links(html_content)

    # Build payload to create page
    payload = {
        "type": "page",
        "title": title,
        "space": {
            "key": space_key
        },
        "body": {
            "storage": {
                "value": html_content,
                "representation": "storage"
            }
        }
    }
    
    # Add parent if specified
    if parent_id:
        payload["ancestors"] = [{"id": parent_id}]

    # POST to create content
    url = f"{base_url}/rest/api/content"
    response = requests.post(url, headers=headers, json=payload)
    
    if response.status_code == 200 or response.status_code == 201:
        data = response.json()
        page_id = data['id']
        print(f"✅ Page created: {base_url}/pages/viewpage.action?pageId={page_id}")
        
        # Upload Mermaid images and update page with correct references
        if image_info_list:
            # Upload images
            for image_info in image_info_list:
                if not image_info['uploaded']:
                    print(f"  📤 Uploading {image_info['image_name']}...")
                    attachment = upload_image_to_confluence(
                        base_url, bearer_token, page_id,
                        image_info['image_path'], image_info['image_name']
                    )
                    if attachment:
                        image_info['uploaded'] = True
                        print(f"  ✅ {image_info['image_name']} uploaded")
            
            # Re-convert the processed markdown (which already has image references) to HTML
            # The processed_md already has Mermaid blocks replaced with image references
            html_content_final = markdown(processed_md, extensions=["tables", "fenced_code", "toc"])
            
            # Replace markdown TOC with Confluence TOC macro
            print(f"📑 Processing table of contents (final pass)...")
            html_content_final = replace_markdown_toc_with_confluence_macro(html_content_final)
            
            # Fix anchor links for Confluence compatibility
            html_content_final = fix_confluence_anchor_links(html_content_final)
            
            # Replace markdown image tags with Confluence macros
            html_content_final = replace_markdown_images_with_confluence_macros(html_content_final, image_info_list)
            
            # Remove any remaining Mermaid code blocks that might have been converted to HTML
            # The markdown library converts ```mermaid blocks to <pre><code class="language-mermaid">
            mermaid_code_pattern = r'<pre><code[^>]*class=["\']language-mermaid["\'][^>]*>.*?</code></pre>'
            if re.search(mermaid_code_pattern, html_content_final, flags=re.IGNORECASE | re.DOTALL):
                print(f"  🧹 Removing remaining Mermaid code blocks from HTML...")
                html_content_final = re.sub(mermaid_code_pattern, '', html_content_final, flags=re.IGNORECASE | re.DOTALL | re.MULTILINE)
            
            # Verify Mermaid code blocks are removed from HTML
            if '```mermaid' in html_content_final.lower() or 'language-mermaid' in html_content_final.lower():
                print(f"  ⚠️  Warning: Mermaid code blocks still present in HTML content")
            
            # Update page with correct image references
            page_info = get_page_info(base_url, bearer_token, page_id)
            if page_info:
                update_payload = {
                    "id": page_id,
                    "type": "page",
                    "title": title,
                    "version": {
                        "number": page_info['version']['number'] + 1
                    },
                    "body": {
                        "storage": {
                            "value": html_content_final,
                            "representation": "storage"
                        }
                    }
                }
                update_url = f"{base_url}/rest/api/content/{page_id}"
                update_response = requests.put(update_url, headers=headers, json=update_payload)
                if update_response.status_code == 200:
                    print(f"✅ Page updated with image references")
                else:
                    print(f"⚠️  Warning: Failed to update page with image references: {update_response.status_code}")
        
        # Clean up temporary files
        for image_info in image_info_list:
            if os.path.exists(image_info['image_path']):
                os.unlink(image_info['image_path'])
        
        return page_id
    else:
        # Clean up temporary files on error
        for image_info in image_info_list:
            if os.path.exists(image_info['image_path']):
                os.unlink(image_info['image_path'])
        print(f"❌ Error creating page: {response.status_code}")
        print(response.text)
        response.raise_for_status()

def update_page(config, page_id, title, markdown_file):
    """Update an existing Confluence page with new content"""
    base_url = config['base_url'].rstrip("/")
    bearer_token = config['bearer_token']
    headers = {
        "Authorization": f"Bearer {bearer_token}",
        "Content-Type": "application/json"
    }

    # Get current page info
    page_info = get_page_info(base_url, bearer_token, page_id)
    if not page_info:
        return None

    # Load markdown
    with open(markdown_file, "r", encoding="utf-8") as f:
        md_text = f.read()
    
    # Process Mermaid diagrams (render and upload images)
    processed_md, image_info_list = process_mermaid_diagrams(
        md_text, base_url, bearer_token, page_id
    )
    
    # Convert markdown to HTML
    html_content = markdown(processed_md, extensions=["tables", "fenced_code", "toc"])
    
    # Replace markdown TOC with Confluence TOC macro
    print(f"📑 Processing table of contents...")
    html_content = replace_markdown_toc_with_confluence_macro(html_content)
    
    # Fix anchor links for Confluence compatibility
    html_content = fix_confluence_anchor_links(html_content)
    
    # Replace markdown image tags with Confluence macros
    html_content = replace_markdown_images_with_confluence_macros(html_content, image_info_list)
    
    # Remove any remaining Mermaid code blocks that might have been converted to HTML
    mermaid_code_pattern = r'<pre><code[^>]*class=["\']language-mermaid["\'][^>]*>.*?</code></pre>'
    if re.search(mermaid_code_pattern, html_content, flags=re.IGNORECASE | re.DOTALL):
        print(f"  🧹 Removing remaining Mermaid code blocks from HTML...")
        html_content = re.sub(mermaid_code_pattern, '', html_content, flags=re.IGNORECASE | re.DOTALL | re.MULTILINE)

    # Build payload to update page
    payload = {
        "id": page_id,
        "type": "page",
        "title": title,
        "version": {
            "number": page_info['version']['number'] + 1
        },
        "body": {
            "storage": {
                "value": html_content,
                "representation": "storage"
            }
        }
    }

    # PUT to update content
    url = f"{base_url}/rest/api/content/{page_id}"
    response = requests.put(url, headers=headers, json=payload)
    
    if response.status_code == 200:
        data = response.json()
        print(f"✅ Page updated: {base_url}/pages/viewpage.action?pageId={data['id']}")
        
        # Clean up temporary image files
        for image_info in image_info_list:
            if os.path.exists(image_info['image_path']):
                os.unlink(image_info['image_path'])
        
        return data['id']
    else:
        # Clean up temporary files on error
        for image_info in image_info_list:
            if os.path.exists(image_info['image_path']):
                os.unlink(image_info['image_path'])
        print(f"❌ Error updating page: {response.status_code}")
        print(response.text)
        response.raise_for_status()

def main():
    parser = argparse.ArgumentParser(description="Create or update a Confluence page from markdown.")
    parser.add_argument("-c", "--config", 
                       default="data/config/confluence.yaml",
                       help="Path to config YAML file (default: data/config/confluence.yaml)")
    parser.add_argument("-s", "--space", 
                       default="~dvreeman",
                       help="Confluence space key (default: ~dvreeman)")
    parser.add_argument("-t", "--title", 
                       required=True,
                       help="Title of the page")
    parser.add_argument("-i", "--input", 
                       required=True,
                       help="Path to the input markdown file")
    parser.add_argument("-p", "--parent", 
                       default="345541283",
                       help="Parent page ID under which to create the new page (default: 345541283)")
    parser.add_argument("-r", "--replace", 
                       help="Page ID to update with new content (if not provided, creates new page)")
    
    args = parser.parse_args()

    # Load config
    try:
        config = load_config(args.config)
    except FileNotFoundError:
        print(f"❌ Config file not found: {args.config}")
        return 1
    except Exception as e:
        print(f"❌ Error loading config: {e}")
        return 1

    # Validate required config fields
    if 'base_url' not in config or 'bearer_token' not in config:
        print("❌ Config file must contain 'base_url' and 'bearer_token' fields")
        return 1

    # Check if input file exists
    try:
        with open(args.input, 'r', encoding='utf-8') as f:
            pass  # Just check if file can be opened
    except FileNotFoundError:
        print(f"❌ Input markdown file not found: {args.input}")
        return 1

    # Create or update page
    try:
        if args.replace:
            print(f"🔄 Updating page {args.replace} with content from {args.input}")
            page_id = update_page(config, args.replace, args.title, args.input)
        else:
            print(f"📄 Creating new page '{args.title}' in space '{args.space}' under parent {args.parent}")
            page_id = create_page(config, args.space, args.title, args.input, args.parent)
        
        if page_id:
            print(f"🎉 Success! Page ID: {page_id}")
            return 0
        else:
            return 1
            
    except Exception as e:
        print(f"❌ Error: {e}")
        return 1

if __name__ == "__main__":
    exit(main())